import { buildSeedFields } from "@/lib/cms/descriptors/page-overrides";
import type { ContentTypeDescriptor } from "@/lib/cms/descriptors/types";
import { contactPageContent } from "@/lib/content/contact-config";
import { FIREBASE_COLLECTIONS } from "@/types/firebase";

/**
 * Page-copy editors for the areas outside the Laptop Bank.
 *
 * Same pattern as lib/content/laptop-bank-page-seeds.ts: the seed stays in code
 * and remains the fallback, the editor's fields are generated by walking it,
 * and stored overrides are merged back on read.
 *
 * WHY GENERATE RATHER THAN KEEP THE HAND-WRITTEN FORMS
 * A hand-written form can only edit the fields somebody remembered to add. A
 * string added to a content object in code is silently uneditable until a
 * developer notices — which is the state every page form in this repo was in.
 * The contact page alone generates 83 editable fields from a 356-line form.
 */

export type PageSeedEntry = {
  /** Firestore document id, and the admin route key after the `page-` prefix. */
  key: string;
  hub: string;
  label: string;
  /** The public route this copy renders on. */
  route: string;
  collection: string;
  description: string;
  /** Paths to rebuild after a write. */
  revalidatePaths: string[];
  seed: Record<string, unknown>;
};

export const PAGE_SEEDS: PageSeedEntry[] = [
  {
    key: "contact",
    hub: "contact",
    label: "Contact page",
    route: "/contact",
    collection: FIREBASE_COLLECTIONS.siteContent,
    description:
      "Every heading, channel, enquiry option and response step on the contact page.",
    revalidatePaths: ["/contact"],
    seed: contactPageContent as unknown as Record<string, unknown>,
  },
];

export function getPageSeedEntry(key: string): PageSeedEntry | undefined {
  return PAGE_SEEDS.find((entry) => entry.key === key);
}

/** One singleton descriptor per page, keyed `page-<key>`. */
export const PAGE_DESCRIPTORS: Record<string, ContentTypeDescriptor> = Object.fromEntries(
  PAGE_SEEDS.map((entry) => [
    `page-${entry.key}`,
    {
      key: `page-${entry.key}`,
      hub: entry.hub,
      collection: entry.collection,
      label: entry.label,
      plural: entry.label,
      description: `${entry.description} Renders on ${entry.route}.`,
      shape: "singleton" as const,
      singletonId: entry.key,
      titleField: "title",
      previewHref: entry.route,
      revalidatePaths: entry.revalidatePaths,
      guidance:
        `Every field here is live copy on ${entry.route}. Leave a field empty to keep the wording the site ships with — an empty field falls back to the built-in text rather than blanking the page. Link destinations and section anchors are not editable here on purpose.`,
      fields: buildSeedFields(entry.seed),
    } satisfies ContentTypeDescriptor,
  ]),
);
