import { buildSeedFields } from "@/lib/cms/descriptors/page-overrides";
import type { ContentTypeDescriptor, FieldDescriptor } from "@/lib/cms/descriptors/types";
import { contactPageContent } from "@/lib/content/contact-config";
import {
  applyForTrainingHub,
  whatWeDoOverviewContent,
  careersHub,
  howItWorksHub,
  partnersHub,
  teamHub,
  trainingCoursesHub,
  whoCanApplyHub,
  whoWeAreHub,
} from "@/lib/content/site-config";
import { newsHubContent } from "@/lib/content/news-config";
import {
  organisationOverviewContent,
  organisationServices,
} from "@/lib/content/organisation-config";
import { partnershipOverviewContent } from "@/lib/content/partnership-config";
import {
  impactOverviewContent,
  impactReportsContent,
  impactSdgsContent,
  impactTestimonialsContent,
} from "@/lib/content/impact-config";
import { FIREBASE_COLLECTIONS } from "@/types/firebase";

/**
 * Page-copy editors for the areas outside the Laptop Bank.
 *
 * Same pattern as lib/content/laptop-bank-page-seeds.ts: the seed stays in code
 * and remains the fallback, the editor's fields are generated by walking it,
 * and stored overrides are merged back on read.
 *
 * WHY GENERATE RATHER THAN KEEP THE HAND-WRITTEN FORMS
 * A hand-written form can only edit the fields somebody remembered to add. A
 * string added to a content object in code is silently uneditable until a
 * developer notices — which is the state every page form in this repo was in.
 * The contact page alone generates 83 editable fields from a 356-line form.
 */

export type PageSeedEntry = {
  /**
   * The admin route key, after the `page-` prefix.
   *
   * Distinct from `docId` because the two namespaces are different: the impact
   * testimonials PAGE and the testimonial RECORDS are separate editors, and
   * `page-testimonials` next to `testimonial` would be a trap for whoever
   * reads the sidebar next.
   */
  key: string;
  /** Firestore document id. */
  docId: string;
  hub: string;
  label: string;
  /** The public route this copy renders on. */
  route: string;
  collection: string;
  description: string;
  /** Paths to rebuild after a write. */
  revalidatePaths: string[];
  seed: Record<string, unknown>;
  /**
   * Fields for keys this page's renderer reads but its seed does not set.
   *
   * The generated editor can only find what the seed contains, so a page that
   * renders `page.heroImage` from a seed with no `heroImage` key had a control
   * in the old hand-written form and none afterwards. Declaring it here brings
   * the control back and allows the merge to store it — see
   * `ContentTypeDescriptor.optionalFields`.
   *
   * Measured rather than guessed: each key below was found by reading the keys
   * the page's own components access and subtracting the keys its seed
   * declares.
   */
  optionalFields?: FieldDescriptor[];
};

const HERO_IMAGE_FIELD: FieldDescriptor = {
  key: "heroImage",
  label: "Hero image URL",
  kind: "url",
  help: "This page ships without a hero image and falls back to a stock one. A URL here replaces it.",
};

const HIGHLIGHTS_EYEBROW_FIELD: FieldDescriptor = {
  key: "highlightsEyebrow",
  label: "Statistics eyebrow",
  kind: "text",
  help: "Small label above the statistics row. Shows “In focus” when empty.",
};

const EXPLORE_FIELDS: FieldDescriptor[] = [
  {
    key: "exploreEyebrow",
    label: "Explore eyebrow",
    kind: "text",
    help: "Small label above the related-pages row at the foot of the page.",
  },
  {
    key: "exploreTitle",
    label: "Explore heading",
    kind: "text",
    help: "Heading above the related-pages row. Shows “Continue exploring” when empty.",
  },
  {
    key: "exploreDescription",
    label: "Explore description",
    kind: "textarea",
    wide: true,
    help: "Sentence under that heading.",
  },
];

const OVERVIEW_VIDEO_FIELDS: FieldDescriptor[] = [
  {
    key: "overviewVideoUrl",
    label: "Overview video URL",
    kind: "url",
    help: "Plays in the overview section. The section shows its image when this is empty.",
  },
  {
    key: "overviewVideoTitle",
    label: "Overview video title",
    kind: "text",
    help: "Accessible title for that video. Falls back to the page title.",
  },
];

/**
 * The eyebrow / heading / description trio a section's framing copy uses.
 *
 * Written as a helper rather than forty literals because the For Organisations
 * pages repeat this exact shape for every section, and a typo in one of forty
 * near-identical keys is invisible — the control simply saves nothing.
 */
function sectionCopyFields(prefix: string, section: string): FieldDescriptor[] {
  return [
    {
      key: `${prefix}Eyebrow`,
      label: `${section} eyebrow`,
      kind: "text",
      help: `Small label above the ${section.toLowerCase()} section. The page shows its built-in wording when empty.`,
    },
    {
      key: `${prefix}Title`,
      label: `${section} heading`,
      kind: "text",
      help: `Heading for the ${section.toLowerCase()} section. Falls back to the shipped wording.`,
    },
    {
      key: `${prefix}Description`,
      label: `${section} description`,
      kind: "textarea",
      wide: true,
      help: `Sentence under the ${section.toLowerCase()} heading.`,
    },
  ];
}

/**
 * Drops any field whose key the seed already sets.
 *
 * `PAGE_DESCRIPTORS` concatenates the walked seed fields with `optionalFields`,
 * so a key present in both would render two controls for one value. Two of the
 * four services ship `packages` in their seed and two do not, and filtering
 * here means one shared declaration serves all four — and stops being a
 * duplicate on its own the day somebody adds the key to a seed.
 */
function withoutSeedKeys(
  fields: FieldDescriptor[],
  seed: Record<string, unknown>,
): FieldDescriptor[] {
  return fields.filter((field) => !(field.key in seed));
}

/**
 * Keys the For Organisations overview renders but its seed does not set.
 *
 * Measured, per the note on `optionalFields`: every key below was confirmed to
 * be read by components/organisations/for-organisations-overview-page.tsx and
 * absent from `organisationOverviewContent`. All fourteen were reachable in the
 * raw-JSON editor this replaces, so leaving them out would have removed
 * capability rather than added it.
 */
const ORG_OVERVIEW_OPTIONAL_FIELDS: FieldDescriptor[] = [
  ...OVERVIEW_VIDEO_FIELDS,
  ...sectionCopyFields("overviewSection", "Overview"),
  ...sectionCopyFields("servicesSection", "Services"),
  ...sectionCopyFields("engagementSection", "Engagement"),
  ...sectionCopyFields("nextStepsSection", "Next steps"),
];

/**
 * Keys a For Organisations service page renders but its seed may not set.
 *
 * Same measurement. `snapshotEyebrow` is deliberately absent: the type
 * declares it and partnership-config.ts even sets it, but no component reads
 * it, so a control for it would save and change nothing.
 */
const ORG_SERVICE_OPTIONAL_FIELDS: FieldDescriptor[] = [
  {
    key: "pricingHeadline",
    label: "Pricing heading",
    kind: "text",
    help: "Heading above the packages. The section is hidden when there are no packages.",
  },
  {
    key: "pricingDescription",
    label: "Pricing description",
    kind: "textarea",
    wide: true,
    help: "Sentence under the pricing heading.",
  },
  {
    key: "packages",
    label: "Packages",
    kind: "list",
    help: "Priced packages for this service. Remove every row to hide the section.",
    itemFields: [
      { key: "name", label: "Package name", kind: "text" },
      { key: "price", label: "Price", kind: "text", help: "Free text — “From $2,500”, “On request”." },
      { key: "description", label: "Description", kind: "textarea", wide: true },
      {
        key: "features",
        label: "What it includes",
        kind: "stringList",
        help: "One item per line.",
      },
      { key: "note", label: "Footnote", kind: "text" },
    ],
  },
  {
    key: "overviewCardBadgeLabel",
    label: "Service-area badge",
    kind: "text",
    help: "Badge on each overview card. Shows “Service area” when empty.",
  },
  ...sectionCopyFields("overviewSection", "Overview"),
  ...sectionCopyFields("howItWorksSection", "How it works"),
  ...sectionCopyFields("caseStudiesSection", "Case studies"),
  {
    key: "packagesSectionEyebrow",
    label: "Packages eyebrow",
    kind: "text",
    help: "Small label above the packages section.",
  },
  ...sectionCopyFields("faqsSection", "FAQs"),
  {
    key: "contactSectionEyebrow",
    label: "Contact eyebrow",
    kind: "text",
    help: "Small label above the enquiry form.",
  },
  ...sectionCopyFields("relatedSection", "Related pages"),
];

export const PAGE_SEEDS: PageSeedEntry[] = [
  {
    key: "contact",
    docId: "contact",
    hub: "contact",
    label: "Contact page",
    route: "/contact",
    collection: FIREBASE_COLLECTIONS.siteContent,
    description:
      "Every heading, channel, enquiry option and response step on the contact page.",
    revalidatePaths: ["/contact"],
    seed: contactPageContent as unknown as Record<string, unknown>,
  },
  {
    key: "impact-overview",
    docId: "overview",
    hub: "our-impact",
    label: "Impact overview",
    route: "/our-impact",
    collection: FIREBASE_COLLECTIONS.impactPages,
    description: "Headings, evidence cards, snapshot and measurement copy on the impact hub.",
    revalidatePaths: ["/our-impact", "/our-impact/reports", "/"],
    seed: impactOverviewContent as unknown as Record<string, unknown>,
  },
  {
    key: "impact-reports",
    docId: "reports",
    hub: "our-impact",
    label: "Impact reports",
    route: "/our-impact/reports",
    collection: FIREBASE_COLLECTIONS.impactPages,
    description: "Report listings copy, download headings and the methodology note.",
    revalidatePaths: ["/our-impact/reports", "/our-impact"],
    seed: impactReportsContent as unknown as Record<string, unknown>,
  },
  {
    key: "impact-testimonials",
    docId: "testimonials",
    hub: "our-impact",
    label: "Impact testimonials page",
    route: "/our-impact/testimonials",
    collection: FIREBASE_COLLECTIONS.impactPages,
    description: "Page wording around the testimonials. The quotes themselves are edited under Testimonials.",
    revalidatePaths: ["/our-impact/testimonials", "/our-impact"],
    seed: impactTestimonialsContent as unknown as Record<string, unknown>,
  },
  {
    key: "impact-sdgs",
    docId: "sdgs",
    hub: "our-impact",
    label: "UN SDGs page",
    route: "/our-impact/sdgs",
    collection: FIREBASE_COLLECTIONS.impactPages,
    description: "Goal descriptions and alignment copy on the SDGs page.",
    revalidatePaths: ["/our-impact/sdgs", "/our-impact"],
    seed: impactSdgsContent as unknown as Record<string, unknown>,
  },
  {
    key: "partner-with-us",
    docId: "_overview",
    hub: "partner-with-us",
    label: "Partner With Us overview",
    route: "/partner-with-us",
    collection: FIREBASE_COLLECTIONS.partnerships,
    description: "Headings, value cards and next-steps copy on the partnership hub.",
    revalidatePaths: ["/partner-with-us"],
    seed: partnershipOverviewContent as unknown as Record<string, unknown>,
    optionalFields: OVERVIEW_VIDEO_FIELDS,
  },
  /**
   * The eight seed-backed site pages, previously edited by
   * components/admin/site-page-form.tsx.
   *
   * Each has a fixed document id in `siteContent` and a seed in
   * lib/content/site-config.ts, which is exactly the singleton pattern already
   * carrying the contact and impact pages — so these needed no new machinery,
   * only the repeatable-list controls that let an editor add a section or a
   * stat the way the old form could.
   *
   * `testimonialsHub` is deliberately absent. It is in `pageFallbacks` but no
   * public page reads it — /our-impact/testimonials renders the impact page
   * content instead — and an editor for content that renders nowhere is worse
   * than no editor: someone would spend an afternoon rewording a page that
   * does not exist.
   */
  {
    key: "who-we-are",
    docId: "who-we-are",
    hub: "who-we-are",
    label: "Who We Are page",
    route: "/who-we-are",
    collection: FIREBASE_COLLECTIONS.siteContent,
    description: "Hero, principles, operating model and next-step copy on the Who We Are hub.",
    revalidatePaths: ["/who-we-are"],
    seed: whoWeAreHub as unknown as Record<string, unknown>,
    optionalFields: [HERO_IMAGE_FIELD, HIGHLIGHTS_EYEBROW_FIELD, ...OVERVIEW_VIDEO_FIELDS],
  },
  {
    key: "team",
    docId: "team",
    hub: "who-we-are",
    label: "Team page",
    route: "/who-we-are/team",
    collection: FIREBASE_COLLECTIONS.siteContent,
    description: "Wording around the team listing. The people themselves are edited under Team.",
    revalidatePaths: ["/who-we-are/team"],
    optionalFields: [HIGHLIGHTS_EYEBROW_FIELD, ...EXPLORE_FIELDS],
    seed: teamHub as unknown as Record<string, unknown>,
  },
  {
    key: "partners",
    docId: "partners",
    hub: "who-we-are",
    label: "Partners page",
    route: "/who-we-are/partners",
    collection: FIREBASE_COLLECTIONS.siteContent,
    description: "Wording around the partner logos. The partners themselves are edited under Partners.",
    revalidatePaths: ["/who-we-are/partners"],
    optionalFields: [HIGHLIGHTS_EYEBROW_FIELD, ...EXPLORE_FIELDS],
    seed: partnersHub as unknown as Record<string, unknown>,
  },
  {
    key: "careers",
    docId: "careers",
    hub: "who-we-are",
    label: "Careers page",
    route: "/who-we-are/careers",
    collection: FIREBASE_COLLECTIONS.siteContent,
    description: "Wording around the vacancies. The roles themselves are edited under Jobs.",
    revalidatePaths: ["/who-we-are/careers"],
    optionalFields: [HIGHLIGHTS_EYEBROW_FIELD, ...EXPLORE_FIELDS],
    seed: careersHub as unknown as Record<string, unknown>,
  },
  {
    key: "apply-for-training",
    docId: "apply-for-training",
    hub: "apply-for-training",
    label: "Apply for Training page",
    route: "/apply-for-training",
    collection: FIREBASE_COLLECTIONS.siteContent,
    description: "The learner pathway landing page: hero, sections, cohorts, process steps and stats.",
    revalidatePaths: ["/apply-for-training"],
    seed: applyForTrainingHub as unknown as Record<string, unknown>,
  },
  {
    key: "apply-who-can-apply",
    docId: "apply-for-training-who-can-apply",
    hub: "apply-for-training",
    label: "Who Can Apply page",
    route: "/apply-for-training/who-can-apply",
    collection: FIREBASE_COLLECTIONS.siteContent,
    description: "Eligibility wording, readiness sections and next-step cards.",
    revalidatePaths: ["/apply-for-training/who-can-apply"],
    seed: whoCanApplyHub as unknown as Record<string, unknown>,
  },
  {
    key: "apply-how-it-works",
    docId: "apply-for-training-how-it-works",
    hub: "apply-for-training",
    label: "How It Works page",
    route: "/apply-for-training/how-it-works",
    collection: FIREBASE_COLLECTIONS.siteContent,
    description: "The training process page: stages, principles and explore copy.",
    revalidatePaths: ["/apply-for-training/how-it-works"],
    optionalFields: [
      {
        key: "principlesHeroTitle",
        label: "Principles hero heading",
        kind: "text",
        help: "Heading on the principles panel. Falls back to the principles title when empty.",
      },
    ],
    seed: howItWorksHub as unknown as Record<string, unknown>,
  },
  {
    key: "apply-courses",
    docId: "apply-for-training-courses",
    hub: "apply-for-training",
    label: "Courses page",
    route: "/apply-for-training/courses",
    collection: FIREBASE_COLLECTIONS.siteContent,
    description: "Wording around the course catalogue, cohorts and application process.",
    revalidatePaths: ["/apply-for-training/courses"],
    seed: trainingCoursesHub as unknown as Record<string, unknown>,
  },
  {
    key: "what-we-do",
    docId: "what-we-do",
    hub: "what-we-do",
    label: "What We Do overview",
    route: "/what-we-do",
    collection: FIREBASE_COLLECTIONS.siteContent,
    description: "Headings, pillars and next-step copy on the What We Do hub. The initiatives themselves are edited under Initiatives.",
    revalidatePaths: ["/what-we-do"],
    seed: whatWeDoOverviewContent as unknown as Record<string, unknown>,
  },
  {
    key: "news-hub",
    docId: "hub",
    hub: "news-and-updates",
    label: "News hub page",
    route: "/news-and-updates",
    collection: FIREBASE_COLLECTIONS.newsPages,
    description: "Wording on the news hub. Articles themselves are edited under Articles.",
    revalidatePaths: ["/news-and-updates"],
    seed: newsHubContent as unknown as Record<string, unknown>,
  },
  /**
   * For Organisations: the overview and its four services, previously edited
   * through components/admin/organisation-content-form.tsx — a single textarea
   * holding the whole page as raw JSON, saved with `JSON.parse`.
   *
   * lib/cms/organisations.ts was already reading through `applyOverrides`, so
   * it understands the flat-path keys this editor writes; these entries are the
   * half of that migration that was never finished.
   */
  {
    key: "for-organisations",
    docId: "_overview",
    hub: "for-organisations",
    label: "For Organisations overview",
    route: "/for-organisations",
    collection: FIREBASE_COLLECTIONS.forOrganisations,
    description: "Hero, statistics, value and engagement cards, and next-steps copy on the organisations hub.",
    revalidatePaths: ["/for-organisations"],
    seed: organisationOverviewContent as unknown as Record<string, unknown>,
    optionalFields: withoutSeedKeys(
      ORG_OVERVIEW_OPTIONAL_FIELDS,
      organisationOverviewContent as unknown as Record<string, unknown>,
    ),
  },
  ...organisationServices.map((service) => ({
    key: service.slug,
    docId: service.slug,
    hub: "for-organisations",
    label: `${service.title} service page`,
    route: `/for-organisations/${service.slug}`,
    collection: FIREBASE_COLLECTIONS.forOrganisations,
    description: `Hero, snapshot, overview cards, process, case studies, packages, FAQs and enquiry copy for ${service.title}.`,
    revalidatePaths: ["/for-organisations", `/for-organisations/${service.slug}`],
    seed: service as unknown as Record<string, unknown>,
    optionalFields: withoutSeedKeys(
      ORG_SERVICE_OPTIONAL_FIELDS,
      service as unknown as Record<string, unknown>,
    ),
  })),
];

export function getPageSeedEntry(key: string): PageSeedEntry | undefined {
  return PAGE_SEEDS.find((entry) => entry.key === key);
}

/**
 * The keys an editor may set on a page even though its seed omits them.
 *
 * Looked up by collection AND document id because document ids are only unique
 * within a collection — `overview` is an impact page here and could be
 * something else elsewhere.
 */
export function pageOptionalKeys(collection: string, docId: string): string[] {
  const entry = PAGE_SEEDS.find((item) => item.collection === collection && item.docId === docId);
  return (entry?.optionalFields ?? []).map((field) => field.key);
}

/** One singleton descriptor per page, keyed `page-<key>`. */
export const PAGE_DESCRIPTORS: Record<string, ContentTypeDescriptor> = Object.fromEntries(
  PAGE_SEEDS.map((entry) => [
    `page-${entry.key}`,
    {
      key: `page-${entry.key}`,
      hub: entry.hub,
      collection: entry.collection,
      label: entry.label,
      plural: entry.label,
      description: `${entry.description} Renders on ${entry.route}.`,
      shape: "singleton" as const,
      singletonId: entry.docId,
      titleField: "title",
      previewHref: entry.route,
      revalidatePaths: entry.revalidatePaths,
      // Carried so the editor can fill its repeatable lists — see the note on
      // ContentTypeDescriptor.seed.
      seed: entry.seed,
      guidance:
        `Every field here is live copy on ${entry.route}. Leave a field empty to keep the wording the site ships with — an empty field falls back to the built-in text rather than blanking the page. Link destinations and section anchors are not editable here on purpose.`,
      optionalFields: entry.optionalFields,
      fields: [...buildSeedFields(entry.seed), ...(entry.optionalFields ?? [])],
    } satisfies ContentTypeDescriptor,
  ]),
);
