import { buildSeedFields } from "@/lib/cms/descriptors/page-overrides";
import type { ContentTypeDescriptor } from "@/lib/cms/descriptors/types";
import { contactPageContent } from "@/lib/content/contact-config";
import {
  applyForTrainingHub,
  whatWeDoOverviewContent,
  careersHub,
  howItWorksHub,
  partnersHub,
  teamHub,
  trainingCoursesHub,
  whoCanApplyHub,
  whoWeAreHub,
} from "@/lib/content/site-config";
import { newsHubContent } from "@/lib/content/news-config";
import { partnershipOverviewContent } from "@/lib/content/partnership-config";
import {
  impactOverviewContent,
  impactReportsContent,
  impactSdgsContent,
  impactTestimonialsContent,
} from "@/lib/content/impact-config";
import { FIREBASE_COLLECTIONS } from "@/types/firebase";

/**
 * Page-copy editors for the areas outside the Laptop Bank.
 *
 * Same pattern as lib/content/laptop-bank-page-seeds.ts: the seed stays in code
 * and remains the fallback, the editor's fields are generated by walking it,
 * and stored overrides are merged back on read.
 *
 * WHY GENERATE RATHER THAN KEEP THE HAND-WRITTEN FORMS
 * A hand-written form can only edit the fields somebody remembered to add. A
 * string added to a content object in code is silently uneditable until a
 * developer notices — which is the state every page form in this repo was in.
 * The contact page alone generates 83 editable fields from a 356-line form.
 */

export type PageSeedEntry = {
  /**
   * The admin route key, after the `page-` prefix.
   *
   * Distinct from `docId` because the two namespaces are different: the impact
   * testimonials PAGE and the testimonial RECORDS are separate editors, and
   * `page-testimonials` next to `testimonial` would be a trap for whoever
   * reads the sidebar next.
   */
  key: string;
  /** Firestore document id. */
  docId: string;
  hub: string;
  label: string;
  /** The public route this copy renders on. */
  route: string;
  collection: string;
  description: string;
  /** Paths to rebuild after a write. */
  revalidatePaths: string[];
  seed: Record<string, unknown>;
};

export const PAGE_SEEDS: PageSeedEntry[] = [
  {
    key: "contact",
    docId: "contact",
    hub: "contact",
    label: "Contact page",
    route: "/contact",
    collection: FIREBASE_COLLECTIONS.siteContent,
    description:
      "Every heading, channel, enquiry option and response step on the contact page.",
    revalidatePaths: ["/contact"],
    seed: contactPageContent as unknown as Record<string, unknown>,
  },
  {
    key: "impact-overview",
    docId: "overview",
    hub: "our-impact",
    label: "Impact overview",
    route: "/our-impact",
    collection: FIREBASE_COLLECTIONS.impactPages,
    description: "Headings, evidence cards, snapshot and measurement copy on the impact hub.",
    revalidatePaths: ["/our-impact", "/our-impact/reports", "/"],
    seed: impactOverviewContent as unknown as Record<string, unknown>,
  },
  {
    key: "impact-reports",
    docId: "reports",
    hub: "our-impact",
    label: "Impact reports",
    route: "/our-impact/reports",
    collection: FIREBASE_COLLECTIONS.impactPages,
    description: "Report listings copy, download headings and the methodology note.",
    revalidatePaths: ["/our-impact/reports", "/our-impact"],
    seed: impactReportsContent as unknown as Record<string, unknown>,
  },
  {
    key: "impact-testimonials",
    docId: "testimonials",
    hub: "our-impact",
    label: "Impact testimonials page",
    route: "/our-impact/testimonials",
    collection: FIREBASE_COLLECTIONS.impactPages,
    description: "Page wording around the testimonials. The quotes themselves are edited under Testimonials.",
    revalidatePaths: ["/our-impact/testimonials", "/our-impact"],
    seed: impactTestimonialsContent as unknown as Record<string, unknown>,
  },
  {
    key: "impact-sdgs",
    docId: "sdgs",
    hub: "our-impact",
    label: "UN SDGs page",
    route: "/our-impact/sdgs",
    collection: FIREBASE_COLLECTIONS.impactPages,
    description: "Goal descriptions and alignment copy on the SDGs page.",
    revalidatePaths: ["/our-impact/sdgs", "/our-impact"],
    seed: impactSdgsContent as unknown as Record<string, unknown>,
  },
  {
    key: "partner-with-us",
    docId: "_overview",
    hub: "partner-with-us",
    label: "Partner With Us overview",
    route: "/partner-with-us",
    collection: FIREBASE_COLLECTIONS.partnerships,
    description: "Headings, value cards and next-steps copy on the partnership hub.",
    revalidatePaths: ["/partner-with-us"],
    seed: partnershipOverviewContent as unknown as Record<string, unknown>,
  },
  /**
   * The eight seed-backed site pages, previously edited by
   * components/admin/site-page-form.tsx.
   *
   * Each has a fixed document id in `siteContent` and a seed in
   * lib/content/site-config.ts, which is exactly the singleton pattern already
   * carrying the contact and impact pages — so these needed no new machinery,
   * only the repeatable-list controls that let an editor add a section or a
   * stat the way the old form could.
   *
   * `testimonialsHub` is deliberately absent. It is in `pageFallbacks` but no
   * public page reads it — /our-impact/testimonials renders the impact page
   * content instead — and an editor for content that renders nowhere is worse
   * than no editor: someone would spend an afternoon rewording a page that
   * does not exist.
   */
  {
    key: "who-we-are",
    docId: "who-we-are",
    hub: "who-we-are",
    label: "Who We Are page",
    route: "/who-we-are",
    collection: FIREBASE_COLLECTIONS.siteContent,
    description: "Hero, principles, operating model and next-step copy on the Who We Are hub.",
    revalidatePaths: ["/who-we-are"],
    seed: whoWeAreHub as unknown as Record<string, unknown>,
  },
  {
    key: "team",
    docId: "team",
    hub: "who-we-are",
    label: "Team page",
    route: "/who-we-are/team",
    collection: FIREBASE_COLLECTIONS.siteContent,
    description: "Wording around the team listing. The people themselves are edited under Team.",
    revalidatePaths: ["/who-we-are/team"],
    seed: teamHub as unknown as Record<string, unknown>,
  },
  {
    key: "partners",
    docId: "partners",
    hub: "who-we-are",
    label: "Partners page",
    route: "/who-we-are/partners",
    collection: FIREBASE_COLLECTIONS.siteContent,
    description: "Wording around the partner logos. The partners themselves are edited under Partners.",
    revalidatePaths: ["/who-we-are/partners"],
    seed: partnersHub as unknown as Record<string, unknown>,
  },
  {
    key: "careers",
    docId: "careers",
    hub: "who-we-are",
    label: "Careers page",
    route: "/who-we-are/careers",
    collection: FIREBASE_COLLECTIONS.siteContent,
    description: "Wording around the vacancies. The roles themselves are edited under Jobs.",
    revalidatePaths: ["/who-we-are/careers"],
    seed: careersHub as unknown as Record<string, unknown>,
  },
  {
    key: "apply-for-training",
    docId: "apply-for-training",
    hub: "apply-for-training",
    label: "Apply for Training page",
    route: "/apply-for-training",
    collection: FIREBASE_COLLECTIONS.siteContent,
    description: "The learner pathway landing page: hero, sections, cohorts, process steps and stats.",
    revalidatePaths: ["/apply-for-training"],
    seed: applyForTrainingHub as unknown as Record<string, unknown>,
  },
  {
    key: "apply-who-can-apply",
    docId: "apply-for-training-who-can-apply",
    hub: "apply-for-training",
    label: "Who Can Apply page",
    route: "/apply-for-training/who-can-apply",
    collection: FIREBASE_COLLECTIONS.siteContent,
    description: "Eligibility wording, readiness sections and next-step cards.",
    revalidatePaths: ["/apply-for-training/who-can-apply"],
    seed: whoCanApplyHub as unknown as Record<string, unknown>,
  },
  {
    key: "apply-how-it-works",
    docId: "apply-for-training-how-it-works",
    hub: "apply-for-training",
    label: "How It Works page",
    route: "/apply-for-training/how-it-works",
    collection: FIREBASE_COLLECTIONS.siteContent,
    description: "The training process page: stages, principles and explore copy.",
    revalidatePaths: ["/apply-for-training/how-it-works"],
    seed: howItWorksHub as unknown as Record<string, unknown>,
  },
  {
    key: "apply-courses",
    docId: "apply-for-training-courses",
    hub: "apply-for-training",
    label: "Courses page",
    route: "/apply-for-training/courses",
    collection: FIREBASE_COLLECTIONS.siteContent,
    description: "Wording around the course catalogue, cohorts and application process.",
    revalidatePaths: ["/apply-for-training/courses"],
    seed: trainingCoursesHub as unknown as Record<string, unknown>,
  },
  {
    key: "what-we-do",
    docId: "what-we-do",
    hub: "what-we-do",
    label: "What We Do overview",
    route: "/what-we-do",
    collection: FIREBASE_COLLECTIONS.siteContent,
    description: "Headings, pillars and next-step copy on the What We Do hub. The initiatives themselves are edited under Initiatives.",
    revalidatePaths: ["/what-we-do"],
    seed: whatWeDoOverviewContent as unknown as Record<string, unknown>,
  },
  {
    key: "news-hub",
    docId: "hub",
    hub: "news-and-updates",
    label: "News hub page",
    route: "/news-and-updates",
    collection: FIREBASE_COLLECTIONS.newsPages,
    description: "Wording on the news hub. Articles themselves are edited under Articles.",
    revalidatePaths: ["/news-and-updates"],
    seed: newsHubContent as unknown as Record<string, unknown>,
  },
];

export function getPageSeedEntry(key: string): PageSeedEntry | undefined {
  return PAGE_SEEDS.find((entry) => entry.key === key);
}

/** One singleton descriptor per page, keyed `page-<key>`. */
export const PAGE_DESCRIPTORS: Record<string, ContentTypeDescriptor> = Object.fromEntries(
  PAGE_SEEDS.map((entry) => [
    `page-${entry.key}`,
    {
      key: `page-${entry.key}`,
      hub: entry.hub,
      collection: entry.collection,
      label: entry.label,
      plural: entry.label,
      description: `${entry.description} Renders on ${entry.route}.`,
      shape: "singleton" as const,
      singletonId: entry.docId,
      titleField: "title",
      previewHref: entry.route,
      revalidatePaths: entry.revalidatePaths,
      // Carried so the editor can fill its repeatable lists — see the note on
      // ContentTypeDescriptor.seed.
      seed: entry.seed,
      guidance:
        `Every field here is live copy on ${entry.route}. Leave a field empty to keep the wording the site ships with — an empty field falls back to the built-in text rather than blanking the page. Link destinations and section anchors are not editable here on purpose.`,
      fields: buildSeedFields(entry.seed),
    } satisfies ContentTypeDescriptor,
  ]),
);
